### ISSUE TITLE
Incorrectly removes some hyphens or dashes

### ISSUE THREAD

**Issue by ademarre** [nathanford/ragadjust#2]
See this sentence near the end of this page: http://markboulton.co.uk/journal/design-abstraction-escalation

> I will have a fuzzy recollection of something – maybe – that is similar.

After ragadjust.js, we have this:

> I will have a fuzzy recollection of something – maybe that is similar.

There are several instances of the problem on that page.

**Comment by nathanford** [comment]
Good catch! Fixed in the latest commit.
