### ISSUE TITLE
WordPress Plugin

### ISSUE THREAD

**Issue by jameskoster** [nathanford/ragadjust#3]
Not reporting an issue, I just came to say that this would make a neat WordPress plugin. Any plans for that? If not I'd be happy to build it if I can find some spare time..!

**Comment by jameskoster** [comment]
Made it anyway :-) http://wordpress.org/plugins/wp-ragadjust/

**Comment by nathanford** [comment]
Saw that on Twitter. Pretty cool. Sorry I couldn't reply sooner, but no worries about building it. That's why I put the script on github! :)
